# Generated by Django 2.2.2 on 2019-06-22 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20190620_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(help_text='Text', max_length=300),
        ),
        migrations.AlterField(
            model_name='post',
            name='company',
            field=models.ForeignKey(help_text='Company', null=True, on_delete=django.db.models.deletion.SET_NULL, to='posts.Company'),
        ),
        migrations.AlterField(
            model_name='post',
            name='industry',
            field=models.ForeignKey(help_text='Industry', null=True, on_delete=django.db.models.deletion.SET_NULL, to='posts.Industry'),
        ),
        migrations.AlterField(
            model_name='post',
            name='role',
            field=models.ForeignKey(help_text='Role', null=True, on_delete=django.db.models.deletion.SET_NULL, to='posts.Role'),
        ),
    ]
