# Generated by Django 2.2.2 on 2019-06-23 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='company',
            field=models.ForeignKey(help_text='Company', null=True, on_delete=django.db.models.deletion.SET_NULL, to='questions.Company'),
        ),
        migrations.AlterField(
            model_name='question',
            name='industry',
            field=models.ForeignKey(help_text='Industry', null=True, on_delete=django.db.models.deletion.SET_NULL, to='questions.Industry'),
        ),
        migrations.AlterField(
            model_name='question',
            name='role',
            field=models.ForeignKey(help_text='Role', null=True, on_delete=django.db.models.deletion.SET_NULL, to='questions.Role'),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(help_text='Title', max_length=200),
        ),
        migrations.AlterField(
            model_name='questionpart',
            name='answer_part',
            field=models.TextField(verbose_name='Answer'),
        ),
        migrations.AlterField(
            model_name='questionpart',
            name='question_part',
            field=models.TextField(help_text='Question'),
        ),
    ]
