# Generated by Django 2.2.2 on 2019-06-23 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_auto_20190623_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='industry',
        ),
        migrations.AlterField(
            model_name='question',
            name='company',
            field=models.ForeignKey(help_text='Company', null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.Company'),
        ),
        migrations.AlterField(
            model_name='question',
            name='industry',
            field=models.ForeignKey(help_text='Industry', null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.Industry'),
        ),
        migrations.AlterField(
            model_name='question',
            name='role',
            field=models.ForeignKey(help_text='Role', null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.Role'),
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='Industry',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
