# Generated by Django 2.2.2 on 2019-06-30 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_auto_20190623_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionpart',
            name='answer_part',
            field=models.TextField(help_text='Answer'),
        ),
    ]
