# Generated by Django 2.2.2 on 2019-06-30 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_difficulty'),
        ('questions', '0005_auto_20190630_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='difficulty',
            field=models.ForeignKey(help_text='Difficulty', null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.Difficulty'),
        ),
    ]
