# Generated by Django 2.2.2 on 2019-06-26 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='birth_date',
        ),
        migrations.AddField(
            model_name='profile',
            name='dob',
            field=models.DateField(blank=True, help_text='Date of Birth', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, help_text='Short Bio', max_length=500),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, help_text='location', max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='skype',
            field=models.CharField(blank=True, help_text='Your Skype username will only be shown to accepted interviews', max_length=250),
        ),
    ]
