# Generated by Django 2.2.2 on 2019-06-28 17:42

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190628_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pic',
            field=models.ImageField(blank=True, upload_to='', verbose_name=accounts.models.user_directory_path),
        ),
    ]
