# Generated by Django 2.2.2 on 2019-06-28 18:19

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20190628_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pic',
            field=models.ImageField(blank=True, upload_to=accounts.models.user_directory_path),
        ),
    ]
