# Generated by Django 2.2.2 on 2019-06-29 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_profile_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='skype',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
