# Generated by Django 2.2.2 on 2019-06-29 20:14

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pic',
            field=models.ImageField(blank=True, help_text='Profile Picture', null=True, upload_to=accounts.models.user_directory_path),
        ),
    ]
