# Generated by Django 2.2.2 on 2019-06-24 16:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='interview_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='interview',
            name='interview_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='interview',
            name='interview_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
