# Generated by Django 2.2.2 on 2019-06-24 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0002_auto_20190624_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interview',
            name='interview_datetime',
        ),
    ]
