# Generated by Django 2.2.2 on 2019-06-24 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0003_remove_interview_interview_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='company',
            field=models.ForeignKey(help_text='Company', null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.Company'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='difficulty',
            field=models.ForeignKey(help_text='Level', null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.Difficulty'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='industry',
            field=models.ForeignKey(help_text='Industry', null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.Industry'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='notes',
            field=models.CharField(help_text='Notes', max_length=50),
        ),
        migrations.AlterField(
            model_name='interview',
            name='partner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='interview',
            name='role',
            field=models.ForeignKey(help_text='Role', null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.Role'),
        ),
    ]
