# Generated by Django 2.2.2 on 2019-06-29 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0005_interview_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='author_skype',
            field=models.CharField(help_text='Skype (only visible to partners)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='partner_skype',
            field=models.CharField(help_text='Skype (only visible to partners)', max_length=50, null=True),
        ),
    ]
