# Generated by Django 2.2.2 on 2019-06-29 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0006_auto_20190629_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interview',
            name='author_skype',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='partner_skype',
        ),
    ]
