# Generated by Django 2.2.2 on 2019-06-30 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0007_auto_20190629_1443'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interview',
            options={'ordering': ['-interview_date']},
        ),
    ]
